### ISSUE TITLE
MaterialDesignThemes dll conflict

### ISSUE THREAD

**Issue by logan12358** [speckleworks/SpeckleDynamo#27]
#### Expected Behaviour
"Speckle Receiver" and "Speckle Sender" nodes should have UI created on them when they're added.

#### Actual Behaviour
"Speckle Receiver" and "Speckle Sender" nodes have no UI created on them when they're added. They look like this:
![screenshot from Dynamo](https://user-images.githubusercontent.com/1195438/41885864-dcc682f6-794d-11e8-824f-977a9e8123b2.png)

The following errors show up in the console, for the receiver:
```
ViewExtensionCommandExecutive ( UniqueId: 4ee155d2-81f5-4404-ad86-070381b020d2, Name: LibraryUI, commandTypeName: CreateNodeCommand )
Failed to apply NodeViewCustomization for Receiver
System.Windows.Markup.XamlParseException:
Could not load file or assembly 'MaterialDesignThemes.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SpeckleDynamo.UserControls.ReceiverUi.InitializeComponent()
   at SpeckleDynamo.UserControls.ReceiverUi..ctor()
   at SpeckleDynamo.ViewCustomizations.ReceiverViewCustomization.CustomizeView(Receiver model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
```

and for the sender:
```
ViewExtensionCommandExecutive ( UniqueId: 3afe1dab-9005-4717-bab3-31164de252f5, Name: LibraryUI, commandTypeName: CreateNodeCommand )
Failed to apply NodeViewCustomization for Sender
System.Windows.Markup.XamlParseException:
Could not load file or assembly 'MaterialDesignThemes.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SpeckleDynamo.UserControls.SenderUi.InitializeComponent()
   at SpeckleDynamo.UserControls.SenderUi..ctor()
   at SpeckleDynamo.SenderViewCustomization.CustomizeView(Sender model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
```

#### Reproduction Steps & System Config (win, osx, web, etc.)
Steps I took:
- Run Windows 10 Pro
- Install Revit 2017.2.3 (through a company installer)
- Install Dynamo 2.0.1.5065
- Install Speckle through the Dynamo package manager
- Set Speckle Account
- Add receiver or sender nodes

Also, I looked in the package directory (`C:\Users\<me>\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\Speckle for Dynamo\bin`) and the file `MaterialDesignThemes.Wpf.dll` seems to be there:
![screenshot of directory listing](https://user-images.githubusercontent.com/1195438/41886127-2d075a28-794f-11e8-8a0b-8f3ee7cdfb71.png)

Maybe I'm missing some dependency? If there's any more information I can provide, just let me know. Any help would be really appreciated 😃

**Comment by alvpickmans** [comment]
Could you check if throws the same exception using Dynamo Sandbox? I don't expect Revit having anything to do with the error but just to double check as I couldn't replicate the issue on my end.

**Comment by teocomi** [comment]
Hi @logan12358, I would try on sandbox as @alvpickmans says, as it might be due to a conflict with another dynamo package or a Revit addin.
Another possibility is that it’s due to a missing .net framework installed on your machine.

**Comment by logan12358** [comment]
Thanks for the suggestions! I tried it with Dynamo Sandbox and it worked. I don't have any other Dynamo packages, but there are some Revit addins that are automatically installed.

I'll check whether I can disable these addins and narrow this down, but it seems like it might just be an issue with my set-up.

**Comment by teocomi** [comment]
👍 keep us in the loop, as if this is due to a dll conflict we might be able to merge the different dlls into one and bypass it...

**Comment by logan12358** [comment]
So I couldn't disable the addins, but I found that they are using MaterialDesignThemes as well. Going by the file size of their dll (is it possible to inspect the version of a dll?), I assume they're using version 2.3.1.953, not 2.4.0.1044.

From the "Manage Packages for Solution" window in Visual Studio, I installed version 2.3.1.953 and rebuilt the project. It now seems to work in Dynamo through Revit!

I'm not very familiar with Windows development (NuGet, dlls, etc.), so I don't know if this is the proper approach? If it is, I can just distribute this rebuilt package internally (until the addins upgrade their dependencies).

**Comment by alvpickmans** [comment]
@logan12358 thanks for the feedback! If you right click on the dll >Properties > Details, it should say the product version. But if you managed to make it work with 2.3.1.953 I guess that should be it.
It would be good to know which addin is it just for reference 

@teocomi merging dlls can work, but we could also "re-create" the UI as there is not too much that is being used from MaterialDesign (?) and save 4MB of package (almost have of it!)

**Comment by logan12358** [comment]
Thanks for the help! And that's a handy tip.

The addin is only developed and used internally at the company I work at, so that's probably not super helpful for anyone else..

**Comment by alvpickmans** [comment]
@teocomi fair enough!

**Comment by logan12358** [comment]
@teocomi that package with the merged dlls works! For anyone else trying to download and use it, be sure to 'unblock' the zip file (right click > Properties > Unblock).

**Comment by mjkkirschner** [comment]
@teocomi how does this work in the end? are the types in your own namespace or are they still the original types (potential for runtime failures).

**Comment by didimitrie** [comment]
> we might have to merge other dlls in the future (ie the websockets one)

I've been following this, and as you know, in Gh and Rhino we've got the same problem with usually `Newtonsoft.json` 🤕 

Besides assembly merging, is there a more elegant solution for perhaps runtime resolving of this? I googled the s*** out of this some time ago, but it was too obscure of a problem for my bandwidth at the time...

**Comment by teocomi** [comment]
I've done it by implementing https://github.com/Fody/Costura, it uses a [different approach to ILMerge](https://blogs.msdn.microsoft.com/microsoft_press/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition/#comment-13163) as it adds the other libraries into the main one as embedded references, which means they are hidden from Dynamo.
Do you see any issue with this @mjkkirschner ? And thanks for chiming in! 😄

**Comment by teocomi** [comment]
Fixed for now, will take effect in the next release.
